Remove Alghorithms
vapor/leaf pull request #222
Opened 2022-11-23 13:30 UTC by dankinsoid

My project build failed with 'No such module 'Alghorithms'' error. This is probably due to the fact that the Algorithms were not added to the target "Leaf" dependencies in the Project file
```swift
 .target(name: "Leaf", dependencies: [
            .product(name: "LeafKit", package: "leaf-kit"),
            .product(name: "Vapor", package: "vapor"),
        ]),
```
But as I see in all the code, Algorithms were used only once and not very justified, so I think it's better to remove it until you really need it

2022-11-27 01:42 UTC, 0xTim commented
What version of Swift are you using etc? All CI is working and no one else seems to have reported any errors.

Regardless, we should fix the underlying error but I'd prefer to keep Swift Algorithms. Since it's used elsewhere in the Vapor stack you'll already have this dependency fetched and compiled

2022-11-27 11:37 UTC, dankinsoid commented
@0xTim  I use swift 5.7
It compiles fine as a package, but doesn't compile as a dependency of another package (Vapor project in my case), I don't know why, but there is a mistake in the package file in my opinion
I change PR to save Algorithms, but fixed package file

2022-11-29 09:03 UTC, 0xTim commented
Original comment:

My project build failed with 'No such module 'Alghorithms'' error. This is probably due to the fact that the Algorithms were not added to the target "Leaf" dependencies in the Project file
```swift
 .target(name: "Leaf", dependencies: [
            .product(name: "LeafKit", package: "leaf-kit"),
            .product(name: "Vapor", package: "vapor"),
        ]),
```
But as I see in all the code, Algorithms were used only once and not very justified, so I think it's better to remove it until you really need it

2022-11-29 09:30 UTC, 0xTim requested changes

2022-11-29 09:30 UTC, 0xTim commented on Sources/Leaf/LeafEncoder.swift
> -import Algorithms
We need to re-add this

2022-11-29 09:50 UTC, 0xTim commented on Sources/Leaf/LeafEncoder.swift
> +            self.init(userInfo: encoder.userInfo, codingPath: encoder.codingPath + [key].compactMap { $0 })
Revert
```suggestion
            self.init(userInfo: encoder.userInfo, codingPath: encoder.codingPath + [key].compacted())
```

2022-11-29 10:04 UTC, 0xTim approved these changes

2022-11-29 10:04 UTC, merged